### ISSUE TITLE
Namespace "goog.ui.AutoComplete.Basic" never provided

### ISSUE THREAD

**Issue by GoogleCodeExporter** [katmoon/bite-project#11]
```
Trying to build from git:

Downloading closure compiler jar file.
Downloading soy compiler and utils.
deps/closure/closure-library/closure/bin/build/closurebuilder.py: Scanning 
paths...
deps/closure/closure-library/closure/bin/build/closurebuilder.py: 1025 sources 
scanned.
deps/closure/closure-library/closure/bin/build/closurebuilder.py: Building 
dependency tree..
Traceback (most recent call last):
  File "deps/closure/closure-library/closure/bin/build/closurebuilder.py", line 256, in <module>
    main()
  File "deps/closure/closure-library/closure/bin/build/closurebuilder.py", line 203, in main
    tree = depstree.DepsTree(sources)
  File "/home/bfife/bite-project/deps/closure/closure-library/closure/bin/build/depstree.py", line 56, in __init__
    raise NamespaceNotFoundError(require, source)
depstree.NamespaceNotFoundError: Namespace "goog.ui.AutoComplete.Basic" never 
provided. Required in Source tools/rpf/extension/src/libs/loaddialog.js


Seems like the closure library was renamed to goog.ui.ac but I don't see 
basic.js anywhere.
```

Original issue reported on code.google.com by `apokaly...@gmail.com` on 24 Oct 2012 at 3:52

**Comment by GoogleCodeExporter** [comment]
```
This project isn't maintained much and only infrequent work is done to update 
for dependencies.  If you try cloning the dev branch it works as of now.  I 
have a TODO to make the dependencies static to avoid these issues in the future.
```

Original comment by `jason.stredwick@gmail.com` on 11 Feb 2013 at 9:48

**Comment by GoogleCodeExporter** [comment]
```
I have also updated prod.  Please let me know if you continue to see your issue 
with the new changes.
```

Original comment by `jason.stredwick@gmail.com` on 1 Mar 2013 at 6:11
- Changed state: **Fixed**
