### ISSUE TITLE
Cant build the project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [katmoon/bite-project#9]
```
~/bite-project $ python build.py
Traceback (most recent call last):
  File "build.py", line 154, in <module>
    main()
  File "build.py", line 52, in main
    result = ParseOptions()
  File "/home/codereview/bite-project/buildhelper.py", line 358, in ParseOptions
    SetupDep(dep_name)
  File "/home/codereview/bite-project/buildhelper.py", line 251, in SetupDep
    ExecuteCommand(dep[CHECKOUT_COMMAND] % (dep[URL], dep[ROOT]))
  File "/home/codereview/bite-project/buildhelper.py", line 215, in ExecuteCommand
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1239, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory



```

Original issue reported on code.google.com by `NIkita.M...@gmail.com` on 9 Sep 2012 at 8:13

**Comment by GoogleCodeExporter** [comment]
```
Sorry for the delay.  I don't monitor this project much anymore.

If you haven't  fix it already, my guess is you don't have one of the required 
tools installed.  I can't tell by your output.  Tools such as mercurial, svn, 
git, etc.

```

Original comment by `jason.stredwick@gmail.com` on 11 Feb 2013 at 9:47

**Comment by GoogleCodeExporter** [comment]
```
Will this be project be supported going forward?
Is Google using this internallly/

We are considering using thie project but not sure if anyone is really using 
this at this point.
```

Original comment by `anil.kad...@gmail.com` on 11 Jun 2013 at 4:10

**Comment by GoogleCodeExporter** [comment]
```
Google no longer supports this project.  I try to address major issues such as 
the move to version two of Chrome Extensions.  However, I usually don't have 
time to support it in general.

As for whether or not it is used internal, it was used by about 6 groups and 
other groups were looking at it but only 1 of the six was a major group.  I 
have since left and no longer know how it is supported or used internally.  My 
guess is that it is no longer used internally.
```

Original comment by `jason.stredwick@gmail.com` on 26 Nov 2013 at 10:20
